# Generated by Django 5.0.3 on 2024-03-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrproj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailsModel',
            new_name='Employee',
        ),
    ]
