# Generated by Django 5.0.3 on 2024-03-10 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrproj', '0002_rename_detailsmodel_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='assignDesignation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_id', models.CharField(max_length=100)),
                ('employee_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrproj.employee')),
            ],
        ),
    ]
