# Generated by Django 5.0.3 on 2024-03-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrproj', '0003_employee_employee_number_assigndesignation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100, unique=True),
        ),
    ]
