# Generated by Django 5.0.3 on 2024-03-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrproj', '0006_remove_assigndesignation_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigndesignation',
            name='designation_id',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='department_id',
        ),
        migrations.AddField(
            model_name='assigndesignation',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrproj.designation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrproj.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='assign_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrproj.assigndesignation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(max_length=100),
        ),
    ]
